version: '3.8'

services:
  dash:
    image: mauricenino/dashdot:latest
    container_name: dash
    labels:
      - homepage.group=Supervision
      - homepage.name=dash
      - homepage.icon=https://getdashdot.com/img/logo512.png
      - homepage.href=http://192.168.1.38:834
      - homepage.description=Dash
    restart: unless-stopped
    privileged: true
    ports:
      - '834:3001'
    volumes:
      - /:/mnt/host:ro
      
  homeassistant:
    image: homeassistant/home-assistant:2024.5
    container_name: homeassistant
    labels:
      - homepage.group=Domotique
      - homepage.name=homeassistant
      - homepage.icon=https://static-00.iconduck.com/assets.00/home-assistant-icon-2048x2048-ar79ra8x.png
      - homepage.href=http://192.168.1.38:8123/dashboard-dashboard/default_view
      - homepage.description=Home Assistant
    volumes:
      - /DATA/AppData/homeassistant/config:/config
    ports:
      - "8123:8123"
    networks:
      - home_net

  overseerr:
    image: linuxserver/overseerr:1.33.2
    container_name: overseerr
    labels:
      - diun.enable=true
      - homepage.group=Film et serie
      - homepage.name=overseerr
      - homepage.icon=https://static-00.iconduck.com/assets.00/overseerr-icon-512x512-i9uxvsi3.png
      - homepage.href=http://192.168.1.38:5055/
      - homepage.description=Oversseer
    volumes:
      - /DATA/AppData/overseerr/config:/config
    ports:
      - "5055:5055"
    networks:
      - home_net

  prowlarr:
    image: linuxserver/prowlarr:1.9.4
    container_name: prowlarr
    labels:
      - homepage.group=Téléchargement
      - homepage.name=prowlarr
      - homepage.icon=https://static-00.iconduck.com/assets.00/prowlarr-icon-1024x1024-vyf0hy1t.png
      - homepage.href=http://192.168.1.38:9696/
      - homepage.description=Prowlarr
    volumes:
      - /DATA/AppData/prowlarr/config:/config
    ports:
      - "9696:9696"
    networks:
      - home_net

  qbittorrent:
    image: hotio/qbittorrent:release-4.6.2
    container_name: qbittorrent
    labels:
      - homepage.group=Téléchargement
      - homepage.name=qbittorrent
      - homepage.icon=https://static-00.iconduck.com/assets.00/qbittorrent-icon-2048x2048-4u7bykpn.png
      - homepage.href=http://192.168.1.38:8181/
      - homepage.description=Qbittorrent
    volumes:
      - /DATA:/DATA
      - /DATA/AppData/qbittorrent/config:/config
    ports:
      - "8181:8080"
    networks:
      - home_net

  radarr:
    image: linuxserver/radarr:5.4.6
    container_name: radarr
    labels:
      - homepage.group=Téléchargement
      - homepage.name=radarr
      - homepage.icon=https://static-00.iconduck.com/assets.00/radarr-icon-1845x2048-97le6lim.png
      - homepage.href=http://192.168.1.38:7878/
      - homepage.description=Movie management
    volumes:
      - /DATA/AppData/radarr/config:/config
      - /DATA/Downloads:/downloads
      - /DATA/Media/Movies:/movies
    ports:
      - "7878:7878"
    networks:
      - home_net

  sonarr:
    image: linuxserver/sonarr:3.0.10
    container_name: sonarr
    labels:
      - homepage.group=Téléchargement
      - homepage.name=sonarr
      - homepage.icon=https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQHOGTXjcPOCdcTjg7-LKFUh71l5G0z0CFGf81FYVbnnw&s
      - homepage.href=http://192.168.1.38:8989/
      - homepage.description=Series management
      - homepage.widget.type= sonarr
      - homepage.widget.url= http://192.168.1.38:8989
      - homepage.widget.key= 584da5babd7542eb9a07c20c77614849
    volumes:
      - /DATA/AppData/sonarr/config:/config
      - /DATA/Downloads:/downloads
      - /DATA/Media/TV Shows:/tv
    ports:
      - "8989:8989"
    networks:
      - home_net

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - /DATA/AppData/homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock


networks:
  home_net:
    driver: bridge
