version: "3.2"
services:
  radarr:
    image: ghcr.io/hotio/radarr
    container_name: radarr
    volumes:
      - /home/antonin/radarr/config:/config/
      - /home/antonin/radarr/data:/data/
    ports:
     - 7878:7878
    environment:
     - PUID=0
     - PGID=0
     - UMASK=002
     - TZ=Europe/Paris

  sonarr:
    image: ghcr.io/hotio/sonarr
    container_name: sonarr
    volumes:
      - /home/antonin/sonarr/config:/config/
      - /home/antonin/sonarr/data:/data/
    ports:
     - 8989:8989
    environment:
     - PUID=0
     - PGID=0
     - UMASK=002
     - TZ=Europe/Paris

  qbittorrent:
    container_name: qbittorrent
    image: ghcr.io/hotio/qbittorrent
    ports:
      - 8080:8080
    environment:
      - PUID=0
      - PGID=0
      - UMASK=002
      - TZ=Europe/Paris
      - WEBUI_PORTS=8080/tcp,8080/udp
    volumes:
      - /home/antonin/qbittorrent/config:/config/
      - /home/antonin/qbittorrent/data:/data/

  plex:
    container_name: plex
    image: ghcr.io/hotio/plex
    ports:
      - 32400:32400
    environment:
      - PUID=0
      - PGID=0
      - UMASK=002
      - TZ=Europe/Paris
      - PLEX_CLAIM_TOKEN
      - PLEX_ADVERTISE_URL
      - PLEX_NO_AUTH_NETWORKS
      - PLEX_BETA_INSTALL=false
      - PLEX_PURGE_CODECS=false
    volumes:
      - /home/antonin/plex/config:/config/
      - /home/antonin/plex/transcode:/transcode/
      - /home/antonin/plex/data:/data/

  jackett:
    container_name: jackett
    image: ghcr.io/hotio/jackett
    ports:
      - 9117:9117
    environment:
      - PUID=0
      - PGID=0
      - UMASK=002
      - TZ=Europe/Paris
    volumes:
      - /home/antonin/jackett/config:/config/
