version: '3.8'

services:
  dash:
    image: mauricenino/dashdot:latest
    container_name: dash
    labels:
      - homepage.group=Supervision
      - homepage.name=dash
      - homepage.icon=https://getdashdot.com/img/logo512.png
      - homepage.href=http://192.168.1.38:834
      - homepage.description=Dash
    restart: unless-stopped
    privileged: true
    ports:
      - '834:3001'
    volumes:
      - /:/mnt/host:ro
      
  homeassistant:
    image: homeassistant/home-assistant:2024.5
    container_name: homeassistant
    labels:
      - homepage.group=Domotique
      - homepage.name=homeassistant
      - homepage.icon=https://static-00.iconduck.com/assets.00/home-assistant-icon-2048x2048-ar79ra8x.png
      - homepage.href=http://192.168.1.38:8123/dashboard-dashboard/default_view
      - homepage.description=Home Assistant
    volumes:
      - /DATA/AppData/homeassistant/config:/config
    ports:
      - "8123:8123"
    networks:
      - home_net

  overseerr:
    image: linuxserver/overseerr:1.33.2
    container_name: overseerr
    labels:
      - diun.enable=true
      - homepage.group=Film et serie
      - homepage.name=overseerr
      - homepage.icon=https://static-00.iconduck.com/assets.00/overseerr-icon-512x512-i9uxvsi3.png
      - homepage.href=http://192.168.1.38:5055/
      - homepage.description=Oversseer test
    volumes:
      - /DATA/AppData/overseerr/config:/config
    ports:
      - "5055:5055"
    networks:
      - home_net
  

  prowlarr:
    image: linuxserver/prowlarr:1.9.4
    container_name: prowlarr
    labels:
      - homepage.group=Gestion Indexeur
      - homepage.name=prowlarr
      - homepage.icon=https://static-00.iconduck.com/assets.00/prowlarr-icon-1024x1024-vyf0hy1t.png
      - homepage.href=http://192.168.1.38:9696/
      - homepage.description=Prowlarr
    volumes:
      - /DATA/AppData/prowlarr/config:/config
    ports:
      - "9696:9696"
    networks:
      - home_net

  qbittorrent1:
    image: hotio/qbittorrent:release-4.6.2
    container_name: qbittorrent1
    labels:
      - homepage.group=Téléchargement Film
      - homepage.name=qbittorrent1
      - homepage.icon=https://static-00.iconduck.com/assets.00/qbittorrent-icon-2048x2048-4u7bykpn.png
      - homepage.href=http://192.168.1.38:8183/
      - homepage.description=Qbittorrent Film
      - homepage.widget.type=qbittorrent1
      - homepage.widget.url=http://192.168.1.38:8183/
      - homepage.widget.username=admin
      - homepage.widget.password=adminadmin
    volumes:
      - /DATA:/DATA
      - /DATA/AppData/qbittorrent1/config:/config
      - /DATA/Media/Movies:/donwnloadfilm
    ports:
      - "8183:8080"
    networks:
      - home_net
   
  qbittorrent2:
    image: hotio/qbittorrent:release-4.6.2
    container_name: qbittorrent2
    labels:
      - homepage.group=Téléchargement Serie
      - homepage.name=qbittorrent2
      - homepage.icon=https://static-00.iconduck.com/assets.00/qbittorrent-icon-2048x2048-4u7bykpn.png
      - homepage.href=http://192.168.1.38:8182/
      - homepage.description=Qbittorrent Serie
    volumes:
      - /DATA:/DATA
      - /DATA/AppData/qbittorrent2/config:/config
      - /DATA/Media/Serie:/donwnloadserie
    ports:
      - "8182:8080"
    networks:
      - home_net

  radarr:
    image: linuxserver/radarr:5.4.6
    container_name: radarr
    labels:
      - homepage.group=Téléchargement Film
      - homepage.name=radarr
      - homepage.icon=https://static-00.iconduck.com/assets.00/radarr-icon-1845x2048-97le6lim.png
      - homepage.href=http://192.168.1.38:7878/
      - homepage.description=Movie management
      - homapage.widget.type=radarr
      - homepage.widget.type=radarr
      - homepage.widget.url=http://192.168.1.38:7878
      - homepage.widget.key=a88d629b4bca4822a4823d4421b4f3af
    volumes:
      - /DATA/AppData/radarr/config:/config
      - /DATA/Downloads:/downloads
      - /DATA/Media/Movies:/movies
    ports:
      - "7878:7878"
    networks:
      - home_net

  sonarr:
    image: linuxserver/sonarr:3.0.10
    container_name: sonarr
    labels:
      - homepage.group=Téléchargement Serie
      - homepage.name=sonarr
      - homepage.icon=https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQHOGTXjcPOCdcTjg7-LKFUh71l5G0z0CFGf81FYVbnnw&s
      - homepage.href=http://192.168.1.38:8989/
      - homepage.description=Series management
      - homepage.widget.type=sonarr
      - homepage.widget.url=http://192.168.1.38:8989
      - homepage.widget.key=584da5babd7542eb9a07c20c77614849
    volumes:
      - /DATA/AppData/sonarr/config:/config
      - /DATA/Downloads:/downloads
      - /DATA/Media/Serie:/serie
    ports:
      - "8989:8989"
    networks:
      - home_net
 
  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/London
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped
         
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 4000:3000
    volumes:
      - /DATA/AppData/homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock

  laravel.test:
        build:
            context: ./docker/8.3
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: speedtest-tracker-8.3/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - mysql
            - mailpit
            # - pgsql
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'sail-mysql:/var/lib/mysql'
            - './docker/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
    mailpit:
        image: 'axllent/mailpit:latest'
        ports:
            - '${FORWARD_MAILPIT_PORT:-1025}:1025'
            - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
        networks:
            - sail
    # pgsql:
    #     image: 'postgres:15'
    #     ports:
    #         - '${FORWARD_DB_PORT:-5432}:5432'
    #     environment:
    #         PGPASSWORD: '${DB_PASSWORD:-secret}'
    #         POSTGRES_DB: '${DB_DATABASE}'
    #         POSTGRES_USER: '${DB_USERNAME}'
    #         POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
    #     volumes:
    #         - 'sail-pgsql:/var/lib/postgresql/data'
    #         - './docker/pgsql/create-testing-database.sql:/docker-entrypoint-initdb.d/10-create-testing-database.sql'
    #     networks:
    #         - sail
    #     healthcheck:
    #         test:
    #             - CMD
    #             - pg_isready
    #             - '-q'
    #             - '-d'
    #             - '${DB_DATABASE}'
    #             - '-U'
    #             - '${DB_USERNAME}'
    #         retries: 3
    #         timeout: 5s
networks:
    sail:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
    # sail-pgsql:
    #     driver: local


networks:
  home_net:
    driver: bridge
