name: Deploy Docker Compose

on:
  push:
    paths:
      - 'docker-compose.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add server to known_hosts
      run: |
        ssh-keyscan -p 32360 88.173.47.125 >> ~/.ssh/known_hosts

    - name: Copy docker-compose.yml to server
      run: scp -P 32360 docker-compose.yml root@88.173.47.125:/home/sven/Docker-homelab/docker-compose.yml

    - name: Deploy with Docker Compose
      run: ssh -p 32360 root@88.173.47.125 "cd /home/sven/Docker-homelab && docker-compose pull && docker-compose up -d"
