name: Deploy Docker Compose

on:
  push:
    paths:
      - 'docker-compose.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Copy docker-compose.yml to server
      run: scp docker-compose.yml root@192.168.1.38:/home/sven/Docker-homelab/docker-compose.yml

    - name: Deploy with Docker Compose
      run: ssh root@192.168.1.38 "cd /home/sven/Docker-homelab && docker-compose pull && docker-compose up -d"
