name: Deploy Docker Compose

on:
  push:
    paths:
      - 'docker-compose.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Copy docker-compose.yml to server
      run: scp -o UserKnownHostsFile=~/.ssh/known_hosts -P 32360 docker-compose.yml root@88.173.47.125:/home/sven/Docker-homelab/docker-compose.yml

    - name: Deploy with Docker Compose
      run: ssh -o UserKnownHostsFile=~/.ssh/known_hosts -p 32360 root@88.173.47.125 "cd /home/sven/Docker-homelab && docker compose up -d --force-recreate"
